# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wa < Formula
  desc "WhatsApp automation CLI + daemon"
  homepage "https://github.com/yolo-labz/wa"
  version "1.2.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/yolo-labz/wa/releases/download/v1.2.0/wa_1.2.0_darwin_arm64.tar.gz"
      sha256 "d6dc424fb2490764af36c050e452660be07fa5db5a11d72b709179808734352a"

      def install
        bin.install "wa"
        bin.install "wad"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/yolo-labz/wa/releases/download/v1.2.0/wa_1.2.0_linux_amd64.tar.gz"
        sha256 "28d8d7e3f8a3b530d656824622fedf20b24557c8a44238c87dc773ae3e37e197"

        def install
          bin.install "wa"
          bin.install "wad"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/yolo-labz/wa/releases/download/v1.2.0/wa_1.2.0_linux_arm64.tar.gz"
        sha256 "c7ab98c4fa149e87db90412bad4a1a40f6c93f844025fd7f658d13075c5c1735"

        def install
          bin.install "wa"
          bin.install "wad"
        end
      end
    end
  end

  test do
    system "#{bin}/wa", "--version"
  end
end
