# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wa < Formula
  desc "WhatsApp automation CLI + daemon"
  homepage "https://github.com/yolo-labz/wa"
  version "1.0.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/yolo-labz/wa/releases/download/v1.0.0/wa_1.0.0_darwin_arm64.tar.gz"
      sha256 "e3a4cce595ee1b403be33b9b790d7548868980ceaf4924e2f04b2558f546580b"

      def install
        bin.install "wa"
        bin.install "wad"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/yolo-labz/wa/releases/download/v1.0.0/wa_1.0.0_linux_amd64.tar.gz"
        sha256 "05187b1d1925590342b917782befb804bc517d166d6764be25288c5f38da1080"

        def install
          bin.install "wa"
          bin.install "wad"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/yolo-labz/wa/releases/download/v1.0.0/wa_1.0.0_linux_arm64.tar.gz"
        sha256 "e718180b04603ed2906c888b5315f25b4494bbf096bcc69b7d1c87fd94ccb6a8"

        def install
          bin.install "wa"
          bin.install "wad"
        end
      end
    end
  end

  test do
    system "#{bin}/wa", "--version"
  end
end
