# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wa < Formula
  desc "WhatsApp automation CLI + daemon"
  homepage "https://github.com/yolo-labz/wa"
  version "1.0.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/yolo-labz/wa/releases/download/v1.0.1/wa_1.0.1_darwin_arm64.tar.gz"
      sha256 "9a912bb9f10a02b8baf227ddf4428caf2d2e7711101ea92fa02c1ca750aacd05"

      def install
        bin.install "wa"
        bin.install "wad"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/yolo-labz/wa/releases/download/v1.0.1/wa_1.0.1_linux_amd64.tar.gz"
        sha256 "2ca1ab3ebf524523835324997782ca59d9f42a104cb69952b6a179b7b837e6ad"

        def install
          bin.install "wa"
          bin.install "wad"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/yolo-labz/wa/releases/download/v1.0.1/wa_1.0.1_linux_arm64.tar.gz"
        sha256 "b6bea8461c71a190e8ec4ada52b560ca8695ded536d1f9dfe5ad89c5dd1d6893"

        def install
          bin.install "wa"
          bin.install "wad"
        end
      end
    end
  end

  test do
    system "#{bin}/wa", "--version"
  end
end
