# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wa < Formula
  desc "WhatsApp automation CLI + daemon"
  homepage "https://github.com/yolo-labz/wa"
  version "2.0.14"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/yolo-labz/wa/releases/download/v2.0.14/wa_2.0.14_darwin_arm64.tar.gz"
      sha256 "37944cbeb86966ec102ca0c2718cea32d1d526057c7e25511b7a32fc73a94e5b"

      def install
        bin.install "wa"
        bin.install "wad"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/yolo-labz/wa/releases/download/v2.0.14/wa_2.0.14_linux_amd64.tar.gz"
        sha256 "1ab8460c4e7b8da351c5d76b93a15e439c9112a5fde6932139292d924757cb46"

        def install
          bin.install "wa"
          bin.install "wad"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/yolo-labz/wa/releases/download/v2.0.14/wa_2.0.14_linux_arm64.tar.gz"
        sha256 "b03a0c4cdd26b937fa73086936af3c011af1b1e95f3f6031058fa8c789e1acf4"

        def install
          bin.install "wa"
          bin.install "wad"
        end
      end
    end
  end

  test do
    system "#{bin}/wa", "--version"
  end
end
