# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wa < Formula
  desc "WhatsApp automation CLI + daemon"
  homepage "https://github.com/yolo-labz/wa"
  version "2.0.5"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/yolo-labz/wa/releases/download/v2.0.5/wa_2.0.5_darwin_arm64.tar.gz"
      sha256 "75ae363d4016b800a4ede3dbaab717a6b0eb358237efe5645a3d6e46255419e3"

      def install
        bin.install "wa"
        bin.install "wad"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/yolo-labz/wa/releases/download/v2.0.5/wa_2.0.5_linux_amd64.tar.gz"
        sha256 "23a82791d04627d70a3049e5977dea146348b7820516a460854033d448300b56"

        def install
          bin.install "wa"
          bin.install "wad"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/yolo-labz/wa/releases/download/v2.0.5/wa_2.0.5_linux_arm64.tar.gz"
        sha256 "e1315d3bb6a5ff60897eb207da32f60ba72be73ac1c06efa200aa49f8f3634dc"

        def install
          bin.install "wa"
          bin.install "wad"
        end
      end
    end
  end

  test do
    system "#{bin}/wa", "--version"
  end
end
